### ISSUE TITLE
post image cannot be resized

### ISSUE THREAD

**Issue by antnb** [AlxMedia/shapebox#1]
Hi

first of all thank you for providing shape box themes as free themes...themes looks wonderful and I don't have any significant issue so far 

but it seems I cannot resize image within my post content.. which resulted in failed mobile-friendly test

I've installed regenerate thumbnail plugins and don't use any plugin aside from themes mandatory plugin, rank math plugin and auto ads AdSense code on my header

on mobile device the image looks like this

![mobile](https://user-images.githubusercontent.com/83947622/160974037-1c175c9a-380a-449d-8430-f7b1acf1f63f.png)

on desktop the image looks like this
![respons](https://user-images.githubusercontent.com/83947622/160974103-86e7e1ed-495d-48b2-a257-2bb081909be7.jpg)

so on mobile device, my page doesn't passed mobile-friendly test (image doesnt resize according to the device size)

![Animation](https://user-images.githubusercontent.com/83947622/161021098-98917bd4-2340-4016-ade0-d00f3755cc16.gif)

**Comment by AlxMedia** [comment]
Hi! Thanks for reporting the issue. Is there any chance you have a direct link to the page with the issue? It would be easier to troubleshoot to see it directly.

**Comment by AlxMedia** [comment]
Uploaded 1.0.3, should fix this.

**Comment by antnb** [comment]
hello

![Animation](https://user-images.githubusercontent.com/83947622/161020586-d6433158-6c0b-481d-92ff-2971f1fd112d.gif)

affected sample pages is here https://bit.ly/38g8zng

**Comment by AlxMedia** [comment]
Also, if you want to hide the white box for the author image, add this in Customize > Additional CSS:

.blog-card-author,
.blog-single-author { display: none; }

I'll add this as an option in the future.

**Comment by AlxMedia** [comment]
Your site still loads version 1.0.0 for me. Are you sure you've cleared any cache plugin?

**Comment by AlxMedia** [comment]
There seem to be some issue with category pages too? I see the frontpage on all category pages, example: https://www.oktrik.com/category/komputer/ - are you using some other plugin that may break permalinks or something? Author archives work fine: https://www.oktrik.com/author/rosari-j

**Comment by antnb** [comment]
> Your site still loads version 1.0.0 for me. Are you sure you've cleared any cache plugin? https://wordpress.org/themes/shapebox/ Download here if you don't use the auto update.

ah you're correct..i thought the earliest version will be replaced by a new one, theres two Shapebox themes in my dashboard ..i still using v 1.0.0 apparently ...now its fixed, image are displayed correctly now 


Thank you very much

**Comment by AlxMedia** [comment]
Glad to hear it works! :-)
